language: ruby
cache: bundler
sudo: required
rvm:
  - 2.2
  - 2.3
addons:
  apt:
    packages:
    - cmake
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get install build-essential
  - sudo apt-get -qq install g++-5
  - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++
  - g++ --version
  - sudo apt-get install bison
  - wget https://github.com/graphql/libgraphqlparser/archive/v0.4.1.tar.gz
  - tar -xzvf v0.4.1.tar.gz
  - cd libgraphqlparser-0.4.1/ && sudo cmake . && sudo make && sudo make install
  - gem update --system
  - gem install bundler
script:
  - bundle exec rake --trace
